default_install_hook_types: [pre-commit]
default_stages: [pre-commit, manual]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=5000"]
        exclude: ^data/
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
        types: [python]
      - id: trailing-whitespace
        types: [python]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.14
    hooks:
      - id: ruff
        args: ["--fix", "--config=pyproject.toml"]
      - id: ruff-format

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: python -m pytest
        language: system
        pass_filenames: false
        always_run: true
        args:
          - "tests/"
          - "-x"
          - "-q"
