apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgres-metrics
    type: postgres
    url: database:5432
    database: metrics
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    isDefault: true
